name: rabbitmq-test-tool
summary: RabbitMQ-Test-Tool
description: |
  A simple test script to test a RabbitMQ cluster
base: core18
confinement: strict
adopt-info: rabbitmq-test-tool

parts:
  rabbitmq-test-tool:
    plugin: python
    source: .
    build-packages:
      - git
    requirements:
      - requirements.txt
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(bin/get_version.py)"

apps:
  rabbitmq-test-tool:
    command: bin/rabbitmq-test-tool
    plugs:
      - network-bind
