name: rabbitmq-test-tool
version: git
summary: RabbitMQ-Test-Tool
description: |
  A tool to test a RabbitMQ cluster.
base: core18
confinement: strict


parts:
  rabbitmq-test-tool:
    plugin: python
    python-version: python3
    source: .
    requirements:
      - requirements.txt

apps:
  rabbitmq-test-tool:
    command: bin/rabbitmq-test-tool
