name: rabbitmq-test-tool
summary: RabbitMQ-Test-Tool
description: |
  A simple test script to test a RabbitMQ cluster
base: core20
confinement: strict
adopt-info: rabbitmq-test-tool

parts:
  rabbitmq-test-tool:
    plugin: python
    source: .
    requirements:
      - requirements.txt
    override-pull: |
      snapcraftctl pull
      version=$(git describe --tags)
      snapcraftctl set-version "${version#v}"

apps:
  rabbitmq-test-tool:
    command: bin/rabbitmq-test-tool
